/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ColaboradorRouteImport } from './routes/colaborador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColaboradorDashboardRouteImport } from './routes/colaborador.dashboard'
import { Route as AdminRegrasSplitRouteImport } from './routes/admin.regras-split'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminImportacoesRouteImport } from './routes/admin.importacoes'
import { Route as AdminFechamentosRouteImport } from './routes/admin.fechamentos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminColaboradoresRouteImport } from './routes/admin.colaboradores'
import { Route as AdminBonusManualRouteImport } from './routes/admin.bonus-manual'
import { Route as AdminCadastroRouteImport } from './routes/admin.cadastro'
import { Route as AdminImportacoesIdRouteImport } from './routes/admin.importacoes.$id'
import { Route as AdminFechamentosIdRouteImport } from './routes/admin.fechamentos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorRoute = ColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorDashboardRoute = ColaboradorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ColaboradorRoute,
} as any)
const AdminRegrasSplitRoute = AdminRegrasSplitRouteImport.update({
  id: '/regras-split',
  path: '/regras-split',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportacoesRoute = AdminImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFechamentosRoute = AdminFechamentosRouteImport.update({
  id: '/fechamentos',
  path: '/fechamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColaboradoresRoute = AdminColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBonusManualRoute = AdminBonusManualRouteImport.update({
  id: '/bonus-manual',
  path: '/bonus-manual',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastroRoute = AdminCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportacoesIdRoute = AdminImportacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminImportacoesRoute,
} as any)
const AdminFechamentosIdRoute = AdminFechamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFechamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/colaborador': typeof ColaboradorRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/bonus-manual': typeof AdminBonusManualRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/colaboradores': typeof AdminColaboradoresRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fechamentos': typeof AdminFechamentosRouteWithChildren
  '/admin/importacoes': typeof AdminImportacoesRouteWithChildren
  '/admin/posts': typeof AdminPostsRoute
  '/admin/regras-split': typeof AdminRegrasSplitRoute
  '/colaborador/dashboard': typeof ColaboradorDashboardRoute
  '/admin/fechamentos/$id': typeof AdminFechamentosIdRoute
  '/admin/importacoes/$id': typeof AdminImportacoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/colaborador': typeof ColaboradorRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/bonus-manual': typeof AdminBonusManualRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/colaboradores': typeof AdminColaboradoresRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fechamentos': typeof AdminFechamentosRouteWithChildren
  '/admin/importacoes': typeof AdminImportacoesRouteWithChildren
  '/admin/posts': typeof AdminPostsRoute
  '/admin/regras-split': typeof AdminRegrasSplitRoute
  '/colaborador/dashboard': typeof ColaboradorDashboardRoute
  '/admin/fechamentos/$id': typeof AdminFechamentosIdRoute
  '/admin/importacoes/$id': typeof AdminImportacoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/colaborador': typeof ColaboradorRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/bonus-manual': typeof AdminBonusManualRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/colaboradores': typeof AdminColaboradoresRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fechamentos': typeof AdminFechamentosRouteWithChildren
  '/admin/importacoes': typeof AdminImportacoesRouteWithChildren
  '/admin/posts': typeof AdminPostsRoute
  '/admin/regras-split': typeof AdminRegrasSplitRoute
  '/colaborador/dashboard': typeof ColaboradorDashboardRoute
  '/admin/fechamentos/$id': typeof AdminFechamentosIdRoute
  '/admin/importacoes/$id': typeof AdminImportacoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/colaborador'
    | '/login'
    | '/admin/bonus-manual'
    | '/admin/cadastro'
    | '/admin/colaboradores'
    | '/admin/dashboard'
    | '/admin/fechamentos'
    | '/admin/importacoes'
    | '/admin/posts'
    | '/admin/regras-split'
    | '/colaborador/dashboard'
    | '/admin/fechamentos/$id'
    | '/admin/importacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/colaborador'
    | '/login'
    | '/admin/bonus-manual'
    | '/admin/cadastro'
    | '/admin/colaboradores'
    | '/admin/dashboard'
    | '/admin/fechamentos'
    | '/admin/importacoes'
    | '/admin/posts'
    | '/admin/regras-split'
    | '/colaborador/dashboard'
    | '/admin/fechamentos/$id'
    | '/admin/importacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/colaborador'
    | '/login'
    | '/admin/bonus-manual'
    | '/admin/cadastro'
    | '/admin/colaboradores'
    | '/admin/dashboard'
    | '/admin/fechamentos'
    | '/admin/importacoes'
    | '/admin/posts'
    | '/admin/regras-split'
    | '/colaborador/dashboard'
    | '/admin/fechamentos/$id'
    | '/admin/importacoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ColaboradorRoute: typeof ColaboradorRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador': {
      id: '/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof ColaboradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/dashboard': {
      id: '/colaborador/dashboard'
      path: '/dashboard'
      fullPath: '/colaborador/dashboard'
      preLoaderRoute: typeof ColaboradorDashboardRouteImport
      parentRoute: typeof ColaboradorRoute
    }
    '/admin/regras-split': {
      id: '/admin/regras-split'
      path: '/regras-split'
      fullPath: '/admin/regras-split'
      preLoaderRoute: typeof AdminRegrasSplitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importacoes': {
      id: '/admin/importacoes'
      path: '/importacoes'
      fullPath: '/admin/importacoes'
      preLoaderRoute: typeof AdminImportacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fechamentos': {
      id: '/admin/fechamentos'
      path: '/fechamentos'
      fullPath: '/admin/fechamentos'
      preLoaderRoute: typeof AdminFechamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colaboradores': {
      id: '/admin/colaboradores'
      path: '/colaboradores'
      fullPath: '/admin/colaboradores'
      preLoaderRoute: typeof AdminColaboradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bonus-manual': {
      id: '/admin/bonus-manual'
      path: '/bonus-manual'
      fullPath: '/admin/bonus-manual'
      preLoaderRoute: typeof AdminBonusManualRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastro': {
      id: '/admin/cadastro'
      path: '/cadastro'
      fullPath: '/admin/cadastro'
      preLoaderRoute: typeof AdminCadastroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importacoes/$id': {
      id: '/admin/importacoes/$id'
      path: '/$id'
      fullPath: '/admin/importacoes/$id'
      preLoaderRoute: typeof AdminImportacoesIdRouteImport
      parentRoute: typeof AdminImportacoesRoute
    }
    '/admin/fechamentos/$id': {
      id: '/admin/fechamentos/$id'
      path: '/$id'
      fullPath: '/admin/fechamentos/$id'
      preLoaderRoute: typeof AdminFechamentosIdRouteImport
      parentRoute: typeof AdminFechamentosRoute
    }
  }
}

interface AdminFechamentosRouteChildren {
  AdminFechamentosIdRoute: typeof AdminFechamentosIdRoute
}

const AdminFechamentosRouteChildren: AdminFechamentosRouteChildren = {
  AdminFechamentosIdRoute: AdminFechamentosIdRoute,
}

const AdminFechamentosRouteWithChildren =
  AdminFechamentosRoute._addFileChildren(AdminFechamentosRouteChildren)

interface AdminImportacoesRouteChildren {
  AdminImportacoesIdRoute: typeof AdminImportacoesIdRoute
}

const AdminImportacoesRouteChildren: AdminImportacoesRouteChildren = {
  AdminImportacoesIdRoute: AdminImportacoesIdRoute,
}

const AdminImportacoesRouteWithChildren =
  AdminImportacoesRoute._addFileChildren(AdminImportacoesRouteChildren)

interface AdminRouteChildren {
  AdminBonusManualRoute: typeof AdminBonusManualRoute
  AdminCadastroRoute: typeof AdminCadastroRoute
  AdminColaboradoresRoute: typeof AdminColaboradoresRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFechamentosRoute: typeof AdminFechamentosRouteWithChildren
  AdminImportacoesRoute: typeof AdminImportacoesRouteWithChildren
  AdminPostsRoute: typeof AdminPostsRoute
  AdminRegrasSplitRoute: typeof AdminRegrasSplitRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBonusManualRoute: AdminBonusManualRoute,
  AdminCadastroRoute: AdminCadastroRoute,
  AdminColaboradoresRoute: AdminColaboradoresRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFechamentosRoute: AdminFechamentosRouteWithChildren,
  AdminImportacoesRoute: AdminImportacoesRouteWithChildren,
  AdminPostsRoute: AdminPostsRoute,
  AdminRegrasSplitRoute: AdminRegrasSplitRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ColaboradorRouteChildren {
  ColaboradorDashboardRoute: typeof ColaboradorDashboardRoute
}

const ColaboradorRouteChildren: ColaboradorRouteChildren = {
  ColaboradorDashboardRoute: ColaboradorDashboardRoute,
}

const ColaboradorRouteWithChildren = ColaboradorRoute._addFileChildren(
  ColaboradorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ColaboradorRoute: ColaboradorRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
